name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest

    steps:
      - name: Release with release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      # Package and upload the release artifact when a release is created
      - name: Checkout code
        if: ${{ steps.release.outputs.release_created }}
        uses: actions/checkout@v5

      - name: Update marketplace.json version
        if: ${{ steps.release.outputs.release_created }}
        run: |
          VERSION="${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
          jq --arg version "$VERSION" '(.plugins[] | select(.name == "cli-ninja") | .version) = $version' \
            .claude-plugin/marketplace.json > .claude-plugin/marketplace.json.tmp
          mv .claude-plugin/marketplace.json.tmp .claude-plugin/marketplace.json

      - name: Create cli-ninja zip package
        if: ${{ steps.release.outputs.release_created }}
        run: |
          cd cli-ninja
          zip -r ../cli-ninja-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.zip .
          cd ..

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} \
            cli-ninja-${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}.zip \
            --clobber
